### Send POST request with json body
POST http://localhost:9090/ad/send
Content-Type: application/json

{
    "storeId" : "4028b88164f931c70164f931ce490000",
    "price" : "50000",
    "image" : "/111123123213xASSSSxxxx.png"

}

###

