### Send POST request with json body
POST http://localhost:9090/product
Content-Type: application/json

{
  "name": "大汉堡",
  "storeId" : "4028b88164f931c70164f931ce490000",
  "description": "无敌大汉堡",
  "images" :"/img/aaaaa.png",
  "price" : "22.6",
  "quantity" : "50"

}

###


DELETE http://localhost:9090/product/8a5e9d4464fa28820164fa28ac1c0000
Accept: application/json

###
GET http://localhost:9090/product/8a5e9d4464fa28820164fa28ac1c0000
Accept: application/json

###
PUT http://localhost:9090/product
Content-Type: application/json

{
    "id" : "8a5e9d4464fa28820164fa4443840001",
   "name": "大汉堡4",
   "storeId" : "4028b88164f931c70164f931ce490000",
   "description": "无敌大汉堡4",
   "images" :"/img/aaaaa.png",
   "price" : "55.6",
   "quantity" : "70"

}

###
###
GET http://localhost:9090/product
Accept: application/json

###
GET http://localhost:9090/product/store/4028b88164f931c70164f931ce490000
Accept: application/json

###