### Send POST request with json body
POST http://localhost:9090/store/add
Content-Type: application/json

{
  "address": "日本qchina1111",
  "license":"xw4856136874plx",
  "name":"store1",
  "user":{
       "id": "8a5e9d4464fab3820164fab3af420000"
    }
 }
###

### Send POST request with json body
POST http://localhost:8999/store/add
Content-Type: application/json

{
  "address": "arm",
  "license":"xw48d56136874plx",
  "name":"store2",
  "user":{
       "id": "8a5e9d4464fab3820164fab7188e0002"
    }
 }



### Send POST request with json body
POST http://localhost:8999/store/update
Content-Type: application/json

{
  "id":"4028b88164f94e690164f96c5ada0001",
  "address": "testLanceTest"
}

###

### Send POST request with json body
POST http://localhost:8999/store/4028b88164f94e690164f96c5ada0001/info/update
Content-Type: application/json

{
    "logoImage":"test.jpg"
}

###


### Send POST request with json body
GET http://localhost:8999/store/4028b88164f94e690164f96c5ada0001
Accept: application/json

###

### Send POST request with json body
GET http://localhost:8999/store/4028b88164f94e690164f96c5ada0001/info
Accept: application/json

###