### Send POST request with json body
POST http://localhost:8999/user/regist
Content-Type: application/json

{
  "username": "lance",
  "password": "123456"
}

###


GET http://localhost:9090/user/delete/8a5e9d4464ff9b130164ff9d1b430001
Accept: application/json

###
GET http://localhost:9090/user/8a5e9d4464ffa8ef0164ffabf7720000
Accept: application/json

###
POST http://localhost:9090/user/update
Content-Type: application/json

{
  "id" : "8a5e9d4464ffa8ef0164ffad56830002",
  "username": "aaaawwwwwaa",
  "password": "123121",
  "identity" :{
            "id": "8a5e9d4464ffa8ef0164ffad56830003",
          "name" :"identityName1",
          "idCardNumber" : "441302888646546",
          "idCardPic" : "/img/xxxxx.png"

     }
}

###