### Get request with a header
GET http://localhost:8080/contact
Accept: application/json


### Delete request with a header
DELETE http://localhost:8080/contact/4028b88164f9fc990164f9fca01a0000
Accept: application/json



### Send POST request with json body
POST http://localhost:8080/contact/
Content-Type: application/json

{
    "address":"httpAddress",
    "phone":"15019936488"
}

### Send POST request with json body
POST http://localhost:8089/contact/update
Content-Type: application/json

{
    "id":"4028b8816504d77c016504d84ff70001",
    "address":"南方软件园小树林二次测试",
    "phone":"15019936488",
    "createTime":1533308085000
}

###
