### Get all store
GET http://localhost:8089/store
Accept: application/json

###

### Get all store page
GET http://localhost:8089/store?pageNum=2&maxResults=6
Accept: application/json

###

### Get  store
GET http://localhost:8089/store/1
Accept: application/json

###

### Get store product total
GET http://localhost:8080/store/4028b88164fab2b60164fab446160000/prod/
Accept: application/json

###


### Get store product with page
GET http://localhost:8080/store/4028b88164fab2b60164fab446160000/prod/?firstIndex=0&maxResults=2
Accept: application/json

###

### Get ad
GET http://localhost:8080/ad/
Accept: application/json

###

### Get store product with page
GET http://localhost:8999/store/4028b88164fab2b60164fab446160000/rank
Accept: application/json

###

